/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsInternalsSplatRouteImport } from './routes/docs/internals/$'
import { Route as DocsGuidesSplatRouteImport } from './routes/docs/guides/$'
import { Route as DocsGettingStartedInstallationRouteImport } from './routes/docs/getting-started/installation'
import { Route as DocsGettingStartedSplatRouteImport } from './routes/docs/getting-started/$'
import { Route as DocsApiSplatRouteImport } from './routes/docs/api/$'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInternalsSplatRoute = DocsInternalsSplatRouteImport.update({
  id: '/internals/$',
  path: '/internals/$',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuidesSplatRoute = DocsGuidesSplatRouteImport.update({
  id: '/guides/$',
  path: '/guides/$',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedInstallationRoute =
  DocsGettingStartedInstallationRouteImport.update({
    id: '/getting-started/installation',
    path: '/getting-started/installation',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsGettingStartedSplatRoute = DocsGettingStartedSplatRouteImport.update({
  id: '/getting-started/$',
  path: '/getting-started/$',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiSplatRoute = DocsApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/api/$': typeof DocsApiSplatRoute
  '/docs/getting-started/$': typeof DocsGettingStartedSplatRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/guides/$': typeof DocsGuidesSplatRoute
  '/docs/internals/$': typeof DocsInternalsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs': typeof DocsIndexRoute
  '/docs/api/$': typeof DocsApiSplatRoute
  '/docs/getting-started/$': typeof DocsGettingStartedSplatRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/guides/$': typeof DocsGuidesSplatRoute
  '/docs/internals/$': typeof DocsInternalsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/api/$': typeof DocsApiSplatRoute
  '/docs/getting-started/$': typeof DocsGettingStartedSplatRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/guides/$': typeof DocsGuidesSplatRoute
  '/docs/internals/$': typeof DocsInternalsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/$'
    | '/docs/'
    | '/docs/api/$'
    | '/docs/getting-started/$'
    | '/docs/getting-started/installation'
    | '/docs/guides/$'
    | '/docs/internals/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/$'
    | '/docs'
    | '/docs/api/$'
    | '/docs/getting-started/$'
    | '/docs/getting-started/installation'
    | '/docs/guides/$'
    | '/docs/internals/$'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/$'
    | '/docs/'
    | '/docs/api/$'
    | '/docs/getting-started/$'
    | '/docs/getting-started/installation'
    | '/docs/guides/$'
    | '/docs/internals/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/internals/$': {
      id: '/docs/internals/$'
      path: '/internals/$'
      fullPath: '/docs/internals/$'
      preLoaderRoute: typeof DocsInternalsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/guides/$': {
      id: '/docs/guides/$'
      path: '/guides/$'
      fullPath: '/docs/guides/$'
      preLoaderRoute: typeof DocsGuidesSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started/installation': {
      id: '/docs/getting-started/installation'
      path: '/getting-started/installation'
      fullPath: '/docs/getting-started/installation'
      preLoaderRoute: typeof DocsGettingStartedInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started/$': {
      id: '/docs/getting-started/$'
      path: '/getting-started/$'
      fullPath: '/docs/getting-started/$'
      preLoaderRoute: typeof DocsGettingStartedSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api/$': {
      id: '/docs/api/$'
      path: '/api/$'
      fullPath: '/docs/api/$'
      preLoaderRoute: typeof DocsApiSplatRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiSplatRoute: typeof DocsApiSplatRoute
  DocsGettingStartedSplatRoute: typeof DocsGettingStartedSplatRoute
  DocsGettingStartedInstallationRoute: typeof DocsGettingStartedInstallationRoute
  DocsGuidesSplatRoute: typeof DocsGuidesSplatRoute
  DocsInternalsSplatRoute: typeof DocsInternalsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiSplatRoute: DocsApiSplatRoute,
  DocsGettingStartedSplatRoute: DocsGettingStartedSplatRoute,
  DocsGettingStartedInstallationRoute: DocsGettingStartedInstallationRoute,
  DocsGuidesSplatRoute: DocsGuidesSplatRoute,
  DocsInternalsSplatRoute: DocsInternalsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
